apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: ghcr.io/thanos-io/thanos-community-website
  newName: ghcr.io/thanos-io/thanos-community-website
  newTag: 0.0.3
resources:
- ../../base
